version: "3"

services:
    api:
        container_name: api
        build: app
        ports:
            - 80:80
        environment:
            FLASK_ENV: development

    website:
        container_name: website
        build: web
        ports:
            - 3000:3000
        depends_on:
            - api
